name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Using npm
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Install Angular CLI
      run: npm install -g @angular/cli@11.2.13
    - name: npm install CI
      run: npm ci
    - name: Add Angular Cli ghpages
      run: ng add angular-cli-ghpages
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ng deploy --no-silent --base-href=/About-Me/
