name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Using npm
      uses: actions/setup-node@v2
      with:
        node-version: 18.12.1
        cache: 'npm'
    - name: Install Angular CLI
      run: npm install -g @angular/cli@15.0.1
    - name: npm install CI
      run: npm ci
    - name: Add Angular Cli ghpages
      run: ng add angular-cli-ghpages
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ github.token }}
      run: ng deploy --base-href=/About-Me/ --name=${{ secrets.NAME }} --email=${{ secrets.EMAIL }}
